# Generated by Django 4.0.4 on 2022-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
