# Generated by Django 4.0.4 on 2022-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'device',
                'ordering': ('-id',),
            },
        ),
    ]
