# Generated by Django 4.0.4 on 2022-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_device_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fiirst_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
