# Generated by Django 4.0.4 on 2022-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userprofile_fiirst_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('low', 'LOW'), ('middel', 'MIDDEL'), ('hight', 'HIGHT')], default='low', max_length=10),
        ),
    ]
